apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-test-413
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-test-413
    app.kubernetes.io/part-of: fbc-example
  name: fbc-test-413dadb
spec:
  port:
    targetPort: 50051
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: fbc-test-413
    weight: 100
status: {}
