apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-test-413
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-test-413
    app.kubernetes.io/part-of: fbc-example
  name: fbc-test-413
spec:
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    app.kubernetes.io/instance: fbc-test-413
status:
  loadBalancer: {}
